[package]
name = "property-rs"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.72", features = ["full"] }
thiserror = "1.0.63"
proc-macro2 = "1.0"
